### ISSUE TITLE
Development getting started error

### ISSUE THREAD

**Issue by cmawhorter** [auth0/custom-social-connections#13]
I'm trying to use this extension as boilerplate for developing my own but there seem to be a step or two missing with the dev [getting started](https://github.com/auth0/custom-social-connections/tree/8c4422451b23e2f698842d1f32b036278803da2d#prerequisites).

I've cloned the repo > `npm install` > `npm start`.  When I open localhost:3000 though I'm greeted with an error:

```
TypeError: Cannot read property 'data' of undefined
   at /Users/.....snip....../custom-social-connections/dist/custom-social-connections.js:1:773
```

I was expecting to see the custom social ui with all the toggles.  

Is it possible to test locally or is pushing to wt a requirement?

**Comment by fyockm** [comment]
thanks @C45tr0
