### ISSUE TITLE
Slider to enable/disable the social connection per client does not show up on Firefox

### ISSUE THREAD

**Issue by gdestuynder** [auth0/custom-social-connections#19]
This works in Chrome, but not Firefox ;-)

May or may not be related:
```
unreachable code after return statement[Learn More]
browser.min.js:37:6409
uncaught exception: Error loading https://connect.facebook.net/en_US/fbevents.js
```

Switching Firefox's user-agent to Chrome fixes the issue... ;-)

**Comment by gdestuynder** [comment]
Looking at the code, it seems like reverting this commit:
https://github.com/auth0/custom-social-connections/commit/f113c530bf34a9cc7bc9ea1a1e411b58d0254311#diff-b266a5c2b75fdc676259a608d31982ed

Fixes the issue - cc @jcenturion 

It might be a Firefox thing that has been fixed, causing it to fail on newer versions of Firefox since the commit is from Feb 2016

**Comment by NotMyself** [comment]
This is still an issue ran into it today.
