### ISSUE TITLE
Version Controling the "Fetch User Profile Script"

### ISSUE THREAD

**Issue by jaschaio** [auth0/custom-social-connections#31]
I created an issue within the [auth0 bitbucket extension](https://github.com/auth0-extensions/auth0-bitbucket-deploy/issues/34) but to be honest I am not sure if it is the right place.

Would love if it were possible to set everything within my auth0 account, including the `fetch user profile scripts` under version control.

**Comment by fyockm** [comment]
@jaschaio providing an API for extensions maintenance is on our roadmap, and this request should be enabled as part that effort. we expect this to be available near the end of Q2 of this year, but I cannot guarantee timing.
