### ISSUE TITLE
How do you debug the Fetch User Profile Script?

### ISSUE THREAD

**Issue by shicholas** [auth0/custom-social-connections#43]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'd like to see things like `console.log`, what libraries I can include, and generally anything to help me debug getting a profile.

### Reproduction

Try and create any custom social provider.

### Environment

Any custom social provider using this plugin.

**Comment by shicholas** [comment]
I was able to figure out my issue, but this took much longer than if I could’ve just print stuff.

Closing for now. Thank you,

**Comment by KevinEdry** [comment]
@shicholas So how did you debug the script? I have the same issue.

**Comment by shicholas** [comment]
I just did a bunch of trial and error until it worked, I didn't have the benefit of logging.
