### ISSUE TITLE
Add a field for custom headers

### ISSUE THREAD

**Issue by nicosabena** [auth0/custom-social-connections#9]
The underlying `oauth2` strategy supports a `customHeaders` value for the options, where you can specify custom headers to be send in the OAuth HTTP interactions. `customHeaders` is a hash, with header names and values:

```
    "options": {
      "client_id": "xxxxx",
      "client_secret": "xxxxx",
      "authorizationURL": "xxxx",
      "tokenURL": "xxxx",
      "scope": "",
      "customHeaders": {
          "Header1": "Value2"
          "Header2": "Value2"
      },
      "scripts": {
        "fetchUserProfile": "xxxx"
      }
```

It would be nice if the extension allowed for providing this custom headers.
Being able to set `customHeaders` in a custom connection enables special use cases such as OAuth identity providers that require credentials as [HTTP Basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) (in a `Authorization` header).

**Comment by jcenturion** [comment]
@nicosabena: I've already added support for `customHeaders`. Closing this bug :).

<img width="892" alt="screen shot 2016-06-07 at 5 21 28 pm" src="https://cloud.githubusercontent.com/assets/302314/15873350/b0c65c52-2cd4-11e6-8c9c-b973eb052207.png">

**Comment by nicosabena** [comment]
Thanks!
